# Generated by Django 5.1.1 on 2024-09-27 12:08

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_remove_cook_kitchen_coo_usernam_8e43b7_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dishtype",
            options={"ordering": (django.db.models.functions.text.Lower("name"),)},
        ),
        migrations.AlterField(
            model_name="cook",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="cook",
            name="first_name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="cook",
            name="last_name",
            field=models.CharField(max_length=150),
        ),
    ]
